local components = require("plugins.config.heirline.components")
-- vim.o.cmdheight = 0

return {
  components.Mode,
  -- components.DimSpacer,
  components.Git,
  -- components.DimSpacer,
  components.FileNameBlock,
  components.Diagnostics,
  components.SearchOccurrence,
  components.Fill,
  components.Debugger,
  components.Lsp,
  components.FileType,
  components.Percentage,
  components.Cursor,
}

-- return { -- statusline
--   components.Mode,
--   components.DimSpacer,
--   -- components.RightPadding(components.Mode, 1),
--   components.Git,
--   -- components.RightPadding(components.Git, 1),
--   -- components.RightPadding(components.FileNameBlock, 1),
--   components.FileNameBlock,
--   -- components.RightPadding(components.Diagnostics, 1),
--   components.Diagnostics,
--   -- components.RightPadding(components.Overseer, 1),
--   -- components.RightPadding(components.SearchOccurrence, 0),
--   components.Fill,
--   -- components.MacroRecording,
--   -- components.Fill,
--   -- components.RightPadding(components.ShowCmd),
--   components.Lsp,
--   -- components.LspProgress,
--   -- components.RightPadding(components.LSPActive),
--   -- components.RightPadding(components.LspProgress, 1),
--   -- components.RightPadding(components.Formatters, 1),
--   -- components.RightPadding(components.SimpleIndicator),
--   components.FileType,
--   -- components.RightPadding(components.FileType, 0),
--   -- components.Ruler,
--   components.Percentage,
--   components.Cursor,
--   -- components.ScrollBar,
-- }
