-- nvim has builtin commenting after 0.10, see `:h commenting`
-- the builting commenting only support line commenting
-- it seems enough for me now :p

-- vim.pack.add({
--   { src = "https://github.com/numToStr/Comment.nvim" },
-- })
--
-- vim.api.nvim_create_autocmd({ "BufReadPost", "BufWritePost", "BufNewFile" }, {
--   group = vim.api.nvim_create_augroup("SetupComment", { clear = true }),
--   once = true,
--   callback = function()
--     require("Comment").setup()
--   end,
-- })
